# Generated by Django 2.1.2 on 2018-10-13 04:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('count', models.IntegerField()),
                ('aisle', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('reserved', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screens.Screen')),
            ],
        ),
    ]
